---
services:
  sonix-qmk-compile:
    image: "jath03/sonix_base_container:latest"
    volumes:
      - "./qmk_firmware:/qmk"
      - "./keymaps/simgunz:/qmk/keyboards/keychron/c1/keymaps/simgunz"
    working_dir: "/qmk"
    command: ["make", "keychron/c1:simgunz"]
