---
version: "2.4"

services:
  sonix-qmk-compile:
    image: "qmkfm/qmk_compiler"
    volumes:
      - "./qmk_firmware:/qmk"
      - "./keymaps/simgunz:/qmk/keyboards/keychron/c1/keymaps/simgunz"
    working_dir: "/qmk"
    command: ["make", "keychron/c1:simgunz"]
