name: Push and Pull Requests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: keychron-c1
    steps:
    - uses: actions/checkout@v2
    - run: ./init.sh
    - run: docker-compose up
